cwlVersion: v1.2
class: Workflow

inputs:
  input_file:
    type: File
    doc: Input file for the workflow

outputs:
  output_file:
    type: File
    doc: Output file generated by the workflow

steps:
  step1:
    run: step1_tool.cwl
    in:
      input_file: input_file
    out:
      - output_file

  step2:
    run: step2_tool.cwl
    in:
      input_file: step1/output_file
    out:
      - output_file

OR

cwlVersion: v1.2
class: Workflow

inputs:
  input_data:
    type: Any
    doc: Input data for the workflow

outputs:
  output_data:
    type: Any
    doc: Output data generated by the workflow

steps:
  step1:
    run: step1_tool.cwl
    in:
      input_data: input_data
    out:
      - output_data

  step2:
    run: step2_tool.cwl
    in:
      input_data: step1/output_data
    out:
      - output_data