# Generated by Django 3.2.5 on 2024-06-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('root_path', models.CharField(default='/tmp/', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(db_index=True, max_length=64, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Running'), (2, 'Complete'), (3, 'Error'), (4, 'Crash')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('runnable', models.BooleanField(default=False)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('cwl_version', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='QueueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('execution_behaviour', models.IntegerField(choices=[(1, 'localhost'), (2, 'GridEngine'), (3, 'R'), (4, 'Python')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='analytics_automated.job')),
                ('validation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_automated.validatortypes')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('in_glob', models.CharField(max_length=256)),
                ('out_glob', models.CharField(max_length=256)),
                ('stdout_glob', models.CharField(max_length=256, null=True)),
                ('executable', models.CharField(max_length=8192)),
                ('incomplete_outputs_behaviour', models.IntegerField(choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], default=3)),
                ('custom_exit_status', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_exit_behaviour', models.IntegerField(blank=True, choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], null=True)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, null=True)),
                ('arguments', models.JSONField(blank=True, null=True)),
                ('stdin', models.CharField(blank=True, max_length=256, null=True)),
                ('stdout', models.CharField(blank=True, max_length=256, null=True)),
                ('stderr', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('doc', models.TextField(blank=True, null=True)),
                ('shell_quote', models.BooleanField(default=False)),
                ('backend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='analytics_automated.backend')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('submission_name', models.CharField(max_length=64)),
                ('UUID', models.CharField(db_index=True, max_length=64, null=True, unique=True)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('input_data', models.FileField(upload_to='')),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Running'), (2, 'Complete'), (3, 'Error'), (4, 'Crash')], default=0)),
                ('last_message', models.CharField(blank=True, default='Submitted', max_length=2046, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('worker_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('hostname', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('step_id', models.IntegerField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='analytics_automated.batch')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_automated.job')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='analytics_automated.job')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics_automated.task')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('step', models.IntegerField()),
                ('previous_step', models.IntegerField(null=True)),
                ('result_data', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=64, null=True)),
                ('message', models.CharField(blank=True, default='Submitted', max_length=256, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics_automated.submission')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_automated.task')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=64)),
                ('default', models.CharField(max_length=64, null=True)),
                ('bool_valued', models.BooleanField(default=False)),
                ('rest_alias', models.CharField(max_length=64, unique=True)),
                ('spacing', models.BooleanField(default=True)),
                ('switchless', models.BooleanField(default=False)),
                ('secondary_files', models.JSONField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='analytics_automated.task')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('step_id', models.IntegerField(null=True)),
                ('message', models.CharField(blank=True, default='Submitted', max_length=2046, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics_automated.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=129, null=True)),
                ('value', models.CharField(max_length=2048, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='analytics_automated.task')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Software'), (1, 'Dataset'), (2, 'Misc.')], default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('version', models.CharField(blank=True, max_length=256, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='analytics_automated.task')),
            ],
        ),
        migrations.CreateModel(
            name='BackendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password', models.CharField(db_index=True, max_length=64, unique=True)),
                ('priority', models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], default=1)),
                ('backend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='analytics_automated.backend')),
            ],
        ),
        migrations.AddField(
            model_name='backend',
            name='queue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='analytics_automated.queuetype'),
        ),
    ]
