# Generated by Django 3.2.5 on 2024-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, 'Misc.'), (0, 'Software'), (1, 'Dataset')], default=0, null=True),
        ),
    ]
