# Generated by Django 3.2.14 on 2024-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_fail_exit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='custom_success_exit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='custom_terminate_exit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
