# Generated by Django 3.2.14 on 2024-07-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_exit_status', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_exit_behaviour', models.IntegerField(blank=True, choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exit', to='analytics_automated.task')),
            ],
        ),
    ]
