# Generated by Django 3.2.14 on 2024-07-25 17:18

from django.db import migrations

def move_custom_exit_to_separate_table(apps, schema_editor):
    Task = apps.get_model('analytics_automated', 'Task')
    CustomExit = apps.get_model('analytics_automated', 'CustomExit')

    for row in Task.objects.all():
        CustomExit.objects.create(task=row, custom_exit_status=row.custom_exit_status, custom_exit_behaviour=row.custom_exit_behaviour)

class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0002_add_custom_exit_table'),
    ]

    operations = [
        migrations.RunPython(move_custom_exit_to_separate_table),
    ]
