# Generated by Django 3.2.14 on 2024-07-25 20:16

from django.db import migrations

def move_custom_exit_to_new_field(apps, schema_editor):
    Task = apps.get_model('analytics_automated', 'Task')

    for row in Task.objects.filter(custom_exit_status__isnull=False, custom_exit_behaviour__isnull=False):
        if row.custom_exit_behaviour == 0:
            row.custom_success_exit = row.custom_exit_status
            row.save()
        elif row.custom_exit_behaviour == 1:
            row.custom_terminate_exit = row.custom_exit_status
            row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0002_add_custom_exit_field'),
    ]

    operations = [
        migrations.RunPython(move_custom_exit_to_new_field),
    ]
