# Generated by Django 3.2.14 on 2024-07-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0003_move_existing_custom_exit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='custom_exit_behaviour',
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_exit_status',
        ),
    ]
