# Generated by Django 3.2.5 on 2024-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0004_remove_custom_exit_from_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cwl_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cwl_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, 'Misc.'), (0, 'Software'), (1, 'Dataset')], default=0, null=True),
        ),
    ]
