# Generated by Django 3.2.14 on 2024-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0004_remove_custom_exit_from_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='condition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
