# Generated by Django 3.2.14 on 2024-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0004_remove_custom_exit_from_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Software'), (2, 'Misc.'), (1, 'Dataset')], default=0, null=True),
        ),
    ]
