# Generated by Django 3.2.14 on 2024-08-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0005_add_condition_field'),
        ('analytics_automated', '0005_auto_20240730_1929'),
    ]

    operations = [
    ]
