# Generated by Django 3.2.14 on 2024-06-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0063_auto_20210716_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Dataset'), (0, 'Software'), (2, 'Misc.')], default=0, null=True),
        ),
    ]
