# Generated by Django 3.2.5 on 2024-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0064_alter_configuration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cwl_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='secondary_files',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='arguments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='initial_work_dir',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='permanent_fail_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='shell_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='stderr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='stdin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='stdout',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='success_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='temporary_fail_codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Software'), (2, 'Misc.'), (1, 'Dataset')], default=0, null=True),
        ),
    ]
