# Generated by Django 3.2.14 on 2024-06-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0065_auto_20240624_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='initial_work_dir',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
