name: Django Tests

on:
  push:
    branches:
      - cwl-testing-framework

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Downgrade pip
        run: |
          python -m pip install --upgrade "pip<24.1"

      - name: Install dependencies
        run: |
          pip install -r requirements/dev.txt

      - name: Create base_secrets.json
        run: |
          echo '{}' > analytics_automated_project/settings/base_secrets.json

      - name: Create dev_secrets.json
        run: |
          echo '{
                   "USER": "test_user",
                   "PASSWORD": "test_pass",
                   "SECRET_KEY": "ANDKSNKJDNSJKFNJKDFJKBFDJKFDBJKDBFJKFBJKFDBJKFBDJKBFJKDBFJKDFBJKFD"
                 }' > analytics_automated_project/settings/dev_secrets.json

      - name: Create logs directory
        run: |
          mkdir -p logs
          touch logs/debug.log

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres container...";
            sleep 5;
          done

      - name: Create test database and role
        run: |
          psql -h localhost -U postgres -c "CREATE ROLE test_user WITH LOGIN PASSWORD 'test_pass';"
          psql -h localhost -U postgres -c "CREATE DATABASE analytics_automated_db OWNER test_user;"
        env:
          PGPASSWORD: postgres

      - name: Run migrations
        run: |
          python manage.py migrate --settings=analytics_automated_project.settings.dev

      - name: Run tests
        run: |
          pytest
